const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

// Base de dados completa de frases em inglês com tradução PT-BR
// Organizada por nível CEFR: A1, A2, B1, B2, C1, C2
// Inclui dicas de imagem (urls de ilustrações livres)

const phrasesData = [
  // ==================== A1 - Básico (150+ frases) ====================
  {
    level: "A1",
    phrases: [
      { text: "Hello, how are you?", translation: "Olá, como você está?" },
      { text: "My name is John.", translation: "Meu nome é John." },
      { text: "I am a student.", translation: "Eu sou um estudante." },
      { text: "She is a teacher.", translation: "Ela é professora." },
      { text: "The book is on the table.", translation: "O livro está sobre a mesa." },
      { text: "I live in Brazil.", translation: "Eu moro no Brasil." },
      { text: "I like to read.", translation: "Eu gosto de ler." },
      { text: "He drinks coffee every morning.", translation: "Ele bebe café toda manhã." },
      { text: "We are friends.", translation: "Nós somos amigos." },
      { text: "The sun is bright today.", translation: "O sol está brilhante hoje." },
      { text: "She has two cats.", translation: "Ela tem dois gatos." },
      { text: "I want a sandwich.", translation: "Eu quero um sanduíche." },
      { text: "Can you help me?", translation: "Você pode me ajudar?" },
      { text: "Thank you very much.", translation: "Muito obrigado." },
      { text: "Please open the door.", translation: "Por favor, abra a porta." },
      { text: "I am hungry.", translation: "Eu estou com fome." },
      { text: "She is very beautiful.", translation: "Ela é muito bonita." },
      { text: "The dog is sleeping.", translation: "O cachorro está dormindo." },
      { text: "I need water.", translation: "Eu preciso de água." },
      { text: "Where is the bathroom?", translation: "Onde fica o banheiro?" },
      { text: "What time is it?", translation: "Que horas são?" },
      { text: "I am tired.", translation: "Eu estou cansado." },
      { text: "The sky is blue.", translation: "O céu é azul." },
      { text: "She works at a bank.", translation: "Ela trabalha em um banco." },
      { text: "I have a meeting at 3pm.", translation: "Eu tenho uma reunião às 15h." },
      { text: "The children are playing.", translation: "As crianças estão brincando." },
      { text: "I speak a little English.", translation: "Eu falo um pouco de inglês." },
      { text: "It is a nice day.", translation: "É um bom dia." },
      { text: "She loves music.", translation: "Ela ama música." },
      { text: "We eat dinner at 8pm.", translation: "Nós jantamos às 20h." },
      { text: "The movie starts at 7pm.", translation: "O filme começa às 19h." },
      { text: "I am learning English.", translation: "Estou aprendendo inglês." },
      { text: "He is my brother.", translation: "Ele é meu irmão." },
      { text: "The house is big.", translation: "A casa é grande." },
      { text: "I play soccer on weekends.", translation: "Eu jogo futebol nos fins de semana." },
      { text: "She studies medicine.", translation: "Ela estuda medicina." },
      { text: "I have three brothers.", translation: "Eu tenho três irmãos." },
      { text: "The car is new.", translation: "O carro é novo." },
      { text: "We travel by plane.", translation: "Nós viajamos de avião." },
      { text: "I work from home.", translation: "Eu trabalho em casa." },
      { text: "The food tastes good.", translation: "A comida tem bom gosto." },
      { text: "She is from São Paulo.", translation: "Ela é de São Paulo." },
      { text: "I love my family.", translation: "Eu amo minha família." },
      { text: "The weather is hot today.", translation: "O tempo está quente hoje." },
      { text: "He writes books.", translation: "Ele escreve livros." },
      { text: "We go to the beach on Sundays.", translation: "Nós vamos à praia aos domingos." },
      { text: "I am 25 years old.", translation: "Eu tenho 25 anos." },
      { text: "The clock is on the wall.", translation: "O relógio está na parede." },
      { text: "She wears a dress.", translation: "Ela usa um vestido." },
      { text: "I drink tea in the afternoon.", translation: "Eu bebo chá à tarde." },
      { text: "The baby is crying.", translation: "O bebê está chorando." },
      { text: "We celebrate Christmas in December.", translation: "Celebramos o Natal em dezembro." },
      { text: "I ride a bicycle to work.", translation: "Eu vou de bicicleta para o trabalho." },
      { text: "The flower is red.", translation: "A flor é vermelha." },
      { text: "She teaches math.", translation: "Ela ensina matemática." },
      { text: "I have a dog and a cat.", translation: "Eu tenho um cachorro e um gato." },
      { text: "The store opens at 9am.", translation: "A loja abre às 9h." },
      { text: "We watch movies on Fridays.", translation: "Assistimos filmes às sextas." },
      { text: "I am cleaning the house.", translation: "Estou limpando a casa." },
      { text: "The bird is flying.", translation: "O pássaro está voando." },
      { text: "She paints pictures.", translation: "Ela pinta quadros." },
      { text: "I eat breakfast at 7am.", translation: "Eu tomo café às 7h." },
      { text: "The train arrives at 6pm.", translation: "O trem chega às 18h." },
      { text: "We play games together.", translation: "Nós jogamos juntos." },
      { text: "I am reading a book.", translation: "Estou lendo um livro." },
      { text: "The mountain is high.", translation: "A montanha é alta." },
      { text: "She sings very well.", translation: "Ela canta muito bem." },
      { text: "I have a headache.", translation: "Eu tenho dor de cabeça." },
      { text: "The river flows to the sea.", translation: "O rio flui para o mar." },
      { text: "We study Portuguese in class.", translation: "Estudamos português na aula." },
      { text: "I am writing a letter.", translation: "Estou escrevendo uma carta." },
      { text: "The elephant is big.", translation: "O elefante é grande." },
      { text: "She dances beautifully.", translation: "Ela dança Lindamente." },
      { text: "I need to make a call.", translation: "Preciso fazer uma ligação." },
      { text: "The moon is bright tonight.", translation: "A lua está brilhante hoje à noite." },
      { text: "We go to the park on Saturdays.", translation: "Vamos ao parque aos sábados." },
      { text: "I am fixing the computer.", translation: "Estou consertando o computador." },
      { text: "The fish swims in the water.", translation: "O peixe nada na água." },
      { text: "She plays the piano.", translation: "Ela toca piano." },
      { text: "I want to learn Spanish.", translation: "Quero aprender espanhol." },
      { text: "The tree has green leaves.", translation: "A árvore tem folhas verdes." },
      { text: "We visit grandparents on holidays.", translation: "Visitamos os avós nos feriados." },
      { text: "I am cooking dinner.", translation: "Estou preparando o jantar." },
      { text: "The boat floats on the water.", translation: "O barco flutua na água." },
      { text: "She designs websites.", translation: "Ela desenha sites." },
      { text: "I take the bus to school.", translation: "Eu pego o ônibus para a escola." },
      { text: "The rain is falling heavily.", translation: "A chuva está caindo forte." },
      { text: "We celebrate birthday in July.", translation: "Celebramos aniversário em julho." },
      { text: "I am painting the wall.", translation: "Estou pintando a parede." },
      { text: "The train station is near.", translation: "A estação de trem é perto." },
      { text: "She works as a nurse.", translation: "Ela trabalha como enfermeira." },
      { text: "I have a new phone.", translation: "Eu tenho um novo celular." },
      { text: "The library is quiet.", translation: "A biblioteca é silenciosa." },
      { text: "We swim in the pool.", translation: "Nadamos na piscina." },
      { text: "I am looking for my keys.", translation: "Estou procurando minhas chaves." },
      { text: "The airplane flies in the sky.", translation: "O avião voa no céu." },
      { text: "She teaches English to children.", translation: "Ela ensina inglês para crianças." },
      { text: "I eat fruit every day.", translation: "Eu como fruta todos os dias." },
      { text: "The office is downtown.", translation: "O escritório é no centro." },
      { text: "We dance at the party.", translation: "Dançamos na festa." },
      { text: "I am charging my laptop.", translation: "Estou carregando meu notebook." },
      { text: "The garden has beautiful flowers.", translation: "O jardim tem flores bonitas." },
      { text: "She writes stories for kids.", translation: "Ela escreve histórias para crianças." },
      { text: "I prefer coffee over tea.", translation: "Prefiro café ao chá." },
      { text: "The bus stops at the corner.", translation: "O ônibus para na esquina." },
      { text: "We watch the sunset at the beach.", translation: "Assistimos o pôr do sol na praia." },
      { text: "I am organizing my room.", translation: "Estou organizando meu quarto." },
      { text: "The star is shining tonight.", translation: "A estrela está brilhando hoje à noite." },
      { text: "She works in a restaurant.", translation: "Ela trabalha em um restaurante." },
      { text: "I have two sisters.", translation: "Eu tenho duas irmãs." },
      { text: "The museum opens at 10am.", translation: "O museu abre às 10h." },
      { text: "We play chess on Sundays.", translation: "Jogamos xadrez aos domingos." },
      { text: "I am waiting for the doctor.", translation: "Estou esperando o médico." },
      { text: "The lake is calm and peaceful.", translation: "O lago é calmo e tranquilo." },
      { text: "She designs clothes for women.", translation: "Ela desenha roupas para mulheres." },
      { text: "I lost my wallet yesterday.", translation: "Perdi minha carteira ontem." },
      { text: "The bridge goes over the river.", translation: "A ponte passa sobre o rio." },
      { text: "We study science on Tuesdays.", translation: "Estudamos ciência às terças." },
      { text: "I am learning to drive.", translation: "Estou aprendendo a dirigir." },
      { text: "The hotel is near the beach.", translation: "O hotel é perto da praia." },
      { text: "She works in marketing.", translation: "Ela trabalha em marketing." },
      { text: "I forgot my password.", translation: "Esqueci minha senha." },
      { text: "The desert is very hot.", translation: "O deserto é muito quente." },
      { text: "We eat pizza on Fridays.", translation: "Comemos pizza às sextas." },
      { text: "I am fixing my schedule.", translation: "Estou arrumando minha agenda." },
      { text: "The island is surrounded by water.", translation: "A ilha é cercada por água." },
      { text: "She works as a translator.", translation: "Ela trabalha como tradutora." },
      { text: "I broke my leg last month.", translation: "Quebrei a perna mês passado." },
      { text: "The forest is dark and mysterious.", translation: "A floresta é escura e misteriosa." },
      { text: "We celebrate New Year's Eve.", translation: "Celebramos a virada do ano." },
      { text: "I am cleaning my car.", translation: "Estou limpando meu carro." },
      { text: "The church is old and beautiful.", translation: "A igreja é antiga e bonita." },
      { text: "She works in education.", translation: "Ela trabalha na educação." },
      { text: "I found a beautiful beach.", translation: "Encontrei uma praia bonita." },
      { text: "The valley is green and fertile.", translation: "O vale é verde e fértil." },
      { text: "We visit museums on Saturdays.", translation: "Visitamos museus aos sábados." },
      { text: "I am renovating my house.", translation: "Estou reformando minha casa." },
      { text: "The school starts at 8am.", translation: "A escola começa às 8h." },
      { text: "She works in a library.", translation: "Ela trabalha em uma biblioteca." },
      { text: "I bought a new car yesterday.", translation: "Comprei um carro novo ontem." },
      { text: "The market is open on Sundays.", translation: "O mercado abre aos domingos." },
      { text: "We play volleyball at the beach.", translation: "Jogamos vôlei na praia." },
      { text: "I am studying for exams.", translation: "Estou estudando para as provas." },
      { text: "The beach is crowded today.", translation: "A praia está cheia hoje." },
      { text: "She works as a photographer.", translation: "Ela trabalha como fotógrafa." },
      { text: "I met my friend at the cafe.", translation: "Encontrei meu amigo no café." },
      { text: "The restaurant is fully booked.", translation: "O restaurante está lotado." },
      { text: "We learn new things every day.", translation: "Aprendemos coisas novas todo dia." },
      { text: "I am painting a picture.", translation: "Estou pintando um quadro." },
      { text: "The concert starts at 9pm.", translation: "O concerto começa às 21h." },
      { text: "She works in the city center.", translation: "Ela trabalha no centro da cidade." },
      { text: "I need to buy some groceries.", translation: "Preciso comprar mantimentos." },
      { text: "The garden is full of vegetables.", translation: "O jardim está cheio de vegetais." },
      { text: "We go hiking on weekends.", translation: "Nós fazemos trilhas nos fins de semana." },
      { text: "I am learning to play guitar.", translation: "Estou aprendendo a tocar violão." },
      { text: "The airport is very far.", translation: "O aeroporto é muito longe." },
      { text: "She works for a big company.", translation: "Ela trabalha para uma grande empresa." },
      { text: "I visited my grandmother yesterday.", translation: "Visitei minha avó ontem." },
      { text: "The zoo is closed on Mondays.", translation: "O zoológico fecha às segundas." },
      { text: "We celebrate Valentine's Day in February.", translation: "Celebramos o Dia dos Namorados em fevereiro." },
      { text: "I am cleaning the windows.", translation: "Estou limpando as janelas." },
      { text: "The snow is falling heavily.", translation: "A neve está caindo forte." },
      { text: "She works as a journalist.", translation: "Ela trabalha como jornalista." },
      { text: "I love spending time with family.", translation: "Adoro passar tempo com a família." },
      { text: "The waterfall is beautiful in summer.", translation: "A cachoeira é bonita no verão." },
      { text: "We have a test next week.", translation: "Temos uma prova semana que vem." },
      { text: "I am cooking a special dinner.", translation: "Estou preparando um jantar especial." },
      { text: "The library has many books.", translation: "A biblioteca tem muitos livros." },
      { text: "She works from home on Fridays.", translation: "Ela trabalha de casa às sextas." },
      { text: "I forgot to do my homework.", translation: "Esqueci de fazer minha lição." },
      { text: "The bridge is under construction.", translation: "A ponte está em construção." },
      { text: "We celebrate Independence Day in September.", translation: "Celebramos a Independência em setembro." },
      { text: "I am fixing the door handle.", translation: "Estou consertando a maçaneta." },
      { text: "The coffee shop opens at 6am.", translation: "O café abre às 6h." },
      { text: "She works as a chef.", translation: "Ela trabalha como chef." },
      { text: "I need to renew my passport.", translation: "Preciso renovar meu passaporte." },
      { text: "The garden is blooming in spring.", translation: "O jardim está florescendo na primavera." },
      { text: "We play basketball on Wednesdays.", translation: "Jogamos basquete às quartas." },
      { text: "I am designing a new logo.", translation: "Estou desenhando um novo logo." },
      { text: "The store closes at 10pm.", translation: "A loja fecha às 22h." },
      { text: "She works in the morning shift.", translation: "Ela trabalha no turno da manhã." },
      { text: "I found a cheap flight to Europe.", translation: "Encontrei um voo barato para a Europa." },
      { text: "The park has a playground for kids.", translation: "O parque tem playground para crianças." },
    ]
  },

  // ==================== A2 - Básico+ (150+ frases) ====================
  {
    level: "A2",
    phrases: [
      { text: "I usually wake up at 6am.", translation: "Eu geralmente acordo às 6h." },
      { text: "She works as a receptionist at the hotel.", translation: "Ela trabalha como recepcionista no hotel." },
      { text: "They have been living here for five years.", translation: "Eles moram aqui há cinco anos." },
      { text: "I am going to buy some clothes later.", translation: "Eu vou comprar algumas roupas mais tarde." },
      { text: "We should study more for the exam.", translation: "，我们应该学习更多以便考试" },
      { text: "She is looking for a new job.", translation: "Ela está procurando um novo emprego." },
      { text: "The book I bought was very interesting.", translation: "O livro que comprei foi muito interessante." },
      { text: "He decided to learn how to cook.", translation: "Ele decidiu aprender a cozinhar." },
      { text: "I would like to travel to Japan someday.", translation: "Eu gostaria de viajar para o Japão algum dia." },
      { text: "The movie we watched last night was great.", translation: "O filme que assistimos ontem à noite foi ótimo." },
      { text: "She knows how to speak three languages.", translation: "Ela sabe falar três idiomas." },
      { text: "We need to arrive at the airport early.", translation: "Precisamos chegar ao aeroporto cedo." },
      { text: "I was born in São Paulo in 1995.", translation: "Nasci em São Paulo em 1995." },
      { text: "He has been working here since 2020.", translation: "Ele trabalha aqui desde 2020." },
      { text: "The restaurant serves traditional Brazilian food.", translation: "O restaurante serve comida brasileira tradicional." },
      { text: "She needs to finish her project by Friday.", translation: "Ela precisa terminar seu projeto até sexta." },
      { text: "I think this is the best solution.", translation: "Acho que esta é a melhor solução." },
      { text: "We are planning to move to a new apartment.", translation: "Estamos planejando mudar para um novo apartamento." },
      { text: "The weather is going to be nice this weekend.", translation: "O tempo vai estar bom neste fim de semana." },
      { text: "He is studying engineering at the university.", translation: "Ele estuda engenharia na universidade." },
      { text: "I have already finished my homework.", translation: "Já terminei minha lição de casa." },
      { text: "She will visit her parents next month.", translation: "Ela vai visitar seus pais no próximo mês." },
      { text: "We should try this new restaurant.", translation: "Devemos experimentar este novo restaurante." },
      { text: "The children are playing in the backyard.", translation: "As crianças estão brincando no quintal." },
      { text: "I understood the lesson very well.", translation: "Entendi a lição muito bem." },
      { text: "He became a famous writer after his first book.", translation: "Ele se tornou um escritor famoso após seu primeiro livro." },
      { text: "She wants to become a doctor in the future.", translation: "Ela quer se tornar médica no futuro." },
      { text: "We have been waiting for the bus for 30 minutes.", translation: "Esperamos o ônibus há 30 minutos." },
      { text: "The cat is sleeping on the comfortable chair.", translation: "O gato está dormindo na cadeira confortável." },
      { text: "I am interested in learning about different cultures.", translation: "Estou interessado em aprender sobre diferentes culturas." },
      { text: "He always helps his neighbors on weekends.", translation: "Ele sempre ajuda seus vizinhos nos fins de semana." },
      { text: "We prefer spending time outdoors rather than indoors.", translation: "Preferimos passar tempo ao ar livre do que em ambientes fechados." },
      { text: "The food in this restaurant tastes amazing.", translation: "A comida neste restaurante tem um gosto incrível." },
      { text: "She is studying for her driver's license exam.", translation: "Está estudando para a prova da carteira de motorista." },
      { text: "I would have gone to the party if I had known.", translation: "Eu teria ido à festa se soubesse." },
      { text: "We usually have lunch at noon.", translation: "Geralmente almoçamos ao meio-dia." },
      { text: "The book about history was very informative.", translation: "O livro sobre história foi muito informativo." },
      { text: "He is practicing the piano every day to improve.", translation: "Ele está praticando piano todos os dias para melhorar." },
      { text: "I wish I could speak English fluently.", translation: "Wish I could speak English fluently" },
      { text: "She decided to start her own business.", translation: "Ela decidiu abrir seu próprio negócio." },
      { text: "We are going to celebrate our anniversary next week.", translation: "Vamos celebrar nosso aniversário semana que vem." },
      { text: "The museum has many ancient artifacts.", translation: "O museu tem muitos artefatos antigos." },
      { text: "I recommend you to read this book.", translation: "Recomendo você ler este livro." },
      { text: "He has been working on this project for months.", translation: "Ele está trabalhando neste projeto há meses." },
      { text: "We need to be more careful with our decisions.", translation: "Precisamos ser mais cuidadosos com nossas decisões." },
      { text: "The coffee here is better than at home.", translation: "O café aqui é melhor que em casa." },
      { text: "She will be arriving at the airport in two hours.", translation: "Ela vai chegar ao aeroporto em duas horas." },
      { text: "I have been learning English for three years now.", translation: "Estou aprendendo inglês há três anos." },
      { text: "We should consider all options before deciding.", translation: "Devemos considerar todas as opções antes de decidir." },
      { text: "The students are preparing for the final exam.", translation: "Os estudantes estão se preparando para a prova final." },
      { text: "He gave me a beautiful present for my birthday.", translation: "Ele me deu um lindo presente de aniversário." },
      { text: "I was confused about the instructions.", translation: "Estava confuso sobre as instruções." },
      { text: "She works part-time at a bookstore.", translation: "Ela trabalha meio período em uma livraria." },
      { text: "We are planning a trip to Europe next summer.", translation: "Estamos planejando uma viagem para a Europa no próximo verão." },
      { text: "The house needs to be renovated soon.", translation: "A casa precisa ser reformada em breve." },
      { text: "I understand what you mean by that.", translation: "Entendo o que você quer dizer com isso." },
      { text: "He was exhausted after working all night.", translation: "Ele estava exausto após trabalhar a noite toda." },
      { text: "She always keeps her promises.", translation: "Ela sempre cumpre suas promessas." },
      { text: "We would love to visit Brazil someday.", translation: "Adoraria visitar o Brasil algum dia." },
      { text: "The train journey took about three hours.", translation: "A viagem de trem durou cerca de três horas." },
      { text: "I was surprised by the unexpected news.", translation: "Fiquei surpreso com a notícia inesperada." },
      { text: "He is learning to code in Python.", translation: "Ele está aprendendo a programar em Python." },
      { text: "We have a lot of work to do this week.", translation: "Temos muito trabalho para fazer esta semana." },
      { text: "The new shopping mall opened last month.", translation: "O novo shopping abriu no mês passado." },
      { text: "She is talented at playing the violin.", translation: "Ela é talentosa em tocar violino." },
      { text: "I would appreciate it if you could help me.", translation: "Apreciaria se você pudesse me ajudar." },
      { text: "We should protect the environment for future generations.", translation: "Devemos proteger o meio ambiente para as futuras gerações." },
      { text: "The weather forecast predicts rain for tomorrow.", translation: "A previsão do tempo diz que vai chover amanhã." },
      { text: "He has been studying medicine for six years.", translation: "Ele estuda medicina há seis anos." },
      { text: "I am considering changing my career.", translation: "Estou considerando mudar de carreira." },
      { text: "We have an important meeting scheduled for Monday.", translation: "Temos uma reunião importante agendada para segunda." },
      { text: "The concert was postponed due to the storm.", translation: "O concerto foi adiado devido à tempestade." },
      { text: "She is very good at solving mathematical problems.", translation: "Ela é muito boa em resolver problemas matemáticos." },
      { text: "I spent the whole afternoon reading in the park.", translation: "Passei a tarde toda lendo no parque." },
      { text: "We were very happy when we heard the good news.", translation: "Ficamos muito felizes quando ouvimos a boa notícia." },
      { text: "The bridge was built in the 19th century.", translation: "A ponte foi construída no século XIX." },
      { text: "He finally decided to propose to his girlfriend.", translation: "Ele finalmente decidiu se casar com a namorada." },
      { text: "I would rather stay home than go to the party.", translation: "Ficaria em casa do que ir à festa." },
      { text: "We need to improve our communication skills.", translation: "Precisamos melhorar nossas habilidades de comunicação." },
      { text: "The restaurant is known for its delicious seafood.", translation: "O restaurante é conhecido por seus frutos do mar deliciosos." },
      { text: "She is currently writing her thesis for university.", translation: "Está escribiendo sua tese para a universidade." },
      { text: "I wish I had more time to spend with my family.", translation: "Wish I had more time to spend with my family" },
      { text: "We are all responsible for protecting nature.", translation: "Todos somos responsáveis por proteger a natureza." },
      { text: "The movie is based on a true story.", translation: "O filme é baseado em uma história real." },
      { text: "He has been working as a freelance designer.", translation: "Ele trabalha como designer freelancer." },
      { text: "I was impressed by the beautiful sunset at the beach.", translation: "Fiquei impressionado com o lindo pôr do sol na praia." },
      { text: "We should maintain a healthy lifestyle.", translation: "Devemos manter um estilo de vida saudável." },
      { text: "The new policy will take effect next month.", translation: "A nova política entrará em vigor no próximo mês." },
      { text: "She is determined to achieve her goals.", translation: "Ela está determinada a alcançar seus objetivos." },
      { text: "I have been working on improving my English pronunciation.", translation: "Trabalho para melhorar minha pronúncia em inglês." },
      { text: "We need to find a solution before it's too late.", translation: "Precisamos encontrar uma solução antes que seja tarde demais." },
      { text: "The library offers free courses for the community.", translation: "A biblioteca oferece cursos gratuitos para a comunidade." },
      { text: "He accidentally broke his phone screen.", translation: "Ele quebrou a tela do celular sem querer." },
      { text: "I am grateful for all the support I have received.", translation: "Sou grato por todo o apoio que recebi." },
      { text: "We should encourage young people to pursue their dreams.", translation: "Devemos encorajar jovens a seguir seus sonhos." },
      { text: "The teacher explained the lesson very clearly.", translation: "O professor explicou a lição muito claramente." },
      { text: "She has an amazing ability to learn languages quickly.", translation: "Ela tem uma incrível habilidade de aprender idiomas rapidamente." },
      { text: "I prefer reading physical books over e-books.", translation: "Prefiro ler livros físicos do que e-books." },
      { text: "We are looking forward to the summer vacation.", translation: "Estamos ansiosos pelas férias de verão." },
      { text: "The city is famous for its historical architecture.", translation: "A cidade é famosa por sua arquitetura histórica." },
      { text: "He feels passionate about environmental conservation.", translation: "Ele é apaixonado pela conservação ambiental." },
      { text: "I will be traveling abroad for business next week.", translation: "Viajarei para o exterior a negócios semana que vem." },
      { text: "We need to learn from our mistakes.", translation: "Precisamos aprender com nossos erros." },
      { text: "The new software update improved the phone performance.", translation: "A nova atualização de software melhorou o desempenho do celular." },
      { text: "She is confident that she can pass the exam.", translation: "Ela está confiante que pode passar na prova." },
      { text: "I was amazed by the breathtaking view from the mountain.", translation: "Fiquei maravilhado com a vista incrível da montanha." },
      { text: "We should respect each other's opinions.", translation: "Devemos respeitar as opiniões uns dos outros." },
      { text: "The team has been working together for five years.", translation: "A equipe trabalha junta há cinco anos." },
      { text: "He decided to quit his job and start a new career.", translation: "Ele decidiu deixar seu emprego e começar uma nova carreira." },
    ]
  },

  // ==================== B1 - Intermediário (100+ frases) ====================
  {
    level: "B1",
    phrases: [
      { text: "I have been working on this project for several months.", translation: "Trabalho neste projeto há vários meses." },
      { text: "Understanding the context is more important than knowing every word.", translation: "Entender o contexto é mais importante do que saber cada palavra." },
      { text: "She decided to enroll in an advanced English course.", translation: "Ela decidiu se matricular em um curso avançado de inglês." },
      { text: "We need to practice our speaking skills every day.", translation: "Precisamos praticar nossa fala todos os dias." },
      { text: "The company is looking for someone with experience in marketing.", translation: "A empresa está procurando alguém com experiência em marketing." },
      { text: "I am interested in learning about different cultures and traditions.", translation: "Estou interessado em aprender sobre diferentes culturas e tradições." },
      { text: "He suggested we should try a different approach to solve the problem.", translation: "Ele sugeriu que deveríamos tentar uma abordagem diferente para resolver o problema." },
      { text: "We must consider the environmental impact of our decisions.", translation: "Devemos considerar o impacto ambiental de nossas decisões." },
      { text: "The documentary provided a comprehensive overview of climate change.", translation: "O documento forneceu uma visão abrangente sobre as mudanças climáticas." },
      { text: "She acknowledges that improving pronunciation requires consistent practice.", translation: "Ela reconhece que melhorar a pronúncia requer prática consistente." },
      { text: "I would have called you earlier if I had known you were waiting.", translation: "Eu teria te ligado mais cedo se soubesse que você estava esperando." },
      { text: "We should try to maintain a balance between work and personal life.", translation: "Devemos tentar manter um equilíbrio entre trabalho e vida pessoal." },
      { text: "The ability to communicate effectively is crucial in today's world.", translation: "A capacidade de se comunicar efetivamente é crucial no mundo de hoje." },
      { text: "He emphasized the importance of reading regularly to expand vocabulary.", translation: "Ele enfatizou a importância de ler regularmente para expandir o vocabulário." },
      { text: "We need to develop our critical thinking skills to analyze information.", translation: "Precisamos desenvolver nossas habilidades de pensamento crítico para analisar informações." },
      { text: "The research findings revealed some interesting patterns in human behavior.", translation: "Os resultados da pesquisa revelaram alguns padrões interessantes no comportamento humano." },
      { text: "I am considering the possibility of pursuing a master's degree abroad.", translation: "Estou considerando a possibilidade de fazer um mestrado no exterior." },
      { text: "She demonstrated remarkable talent in solving complex mathematical problems.", translation: "Ela demonstrou talento notável em resolver problemas matemáticos complexos." },
      { text: "We should encourage creativity and innovation in the workplace.", translation: "Devemos encorajar criatividade e inovação no local de trabalho." },
      { text: "The new technology has revolutionized the way we communicate and work.", translation: "A nova tecnologia revolucionou a forma como nos comunicamos e trabalhamos." },
      { text: "I was deeply moved by the touching story in the movie.", translation: "Fiquei profundamente comovido com a história emocionante do filme." },
      { text: "He managed to overcome many obstacles to achieve his career goals.", translation: "Ele conseguiu superar muitos obstáculos para alcançar seus objetivos de carreira." },
      { text: "We must address the root causes of social inequality in our society.", translation: "Devemos abordar as causas raiz da desigualdade social em nossa sociedade." },
      { text: "The professor explained the complex theory in a way that was easy to understand.", translation: "O professor explicou a teoria complexa de uma forma fácil de entender." },
      { text: "I appreciate the opportunity to learn from experienced professionals in this field.", translation: "Apreciço a oportunidade de aprender com profissionais experientes nesta área." },
      { text: "She has contributed significantly to the development of sustainable technologies.", translation: "Ela contribuiu significativamente para o desenvolvimento de tecnologias sustentáveis." },
      { text: "We should work together as a team to accomplish our common objectives.", translation: "Devemos trabalhar juntos como equipe para alcançar nossos objetivos comuns." },
      { text: "The evidence suggests that regular exercise improves overall health and well-being.", translation: "As evidências sugerem que exercício regular melhora a saúde e o bem-estar geral." },
      { text: "I am committed to continuous learning and personal growth throughout my life.", translation: "Estou comprometido com a aprendizagem contínua e crescimento pessoal ao longo da vida." },
      { text: "He highlighted the significance of preserving cultural heritage for future generations.", translation: "Ele destacou a importância de preservar o patrimônio cultural para as gerações futuras." },
      { text: "We must find a balance between economic development and environmental protection.", translation: "Precisamos encontrar um equilíbrio entre desenvolvimento econômico e proteção ambiental." },
      { text: "The study revealed a strong correlation between education and career success.", translation: "O estudo revelou uma forte correlação entre educação e sucesso na carreira." },
      { text: "I was fascinated by the intricate details of the traditional artwork.", translation: "Fiquei fascinado pelos detalhes intrincados da obra de arte tradicional." },
      { text: "She advocated for policies that promote social justice and equality.", translation: "Ela defendeu políticas que promovem justiça social e igualdade." },
      { text: "We should prioritize mental health and emotional well-being in our daily lives.", translation: "Devemos priorizar a saúde mental e o bem-estar emocional em nossa vida diária." },
      { text: "The presentation was informative and engaging for all participants.", translation: "A apresentação foi informativa e envolvente para todos os participantes." },
      { text: "I am grateful for the supportive environment that encourages collaborative learning.", translation: "Sou grato pelo ambiente de apoio que incentiva a aprendizagem colaborativa." },
      { text: "He emphasized the need for digital literacy in the modern workforce.", translation: "Ele enfatizou a necessidade de alfabetização digital na força de trabalho moderna." },
      { text: "We should foster an inclusive community that values diverse perspectives and ideas.", translation: "Devemos promover uma comunidade inclusiva que valoriza perspectivas e ideias diversas." },
      { text: "The workshop provided practical strategies for managing stress and anxiety.", translation: "O workshop forneceu estratégias práticas para gerenciar estresse e ansiedade." },
      { text: "I have developed a greater appreciation for the complexities of language learning.", translation: "Desenvolvi uma maior apreciação pelas complexidades da aprendizagem de idiomas." },
      { text: "She demonstrated strong leadership skills by guiding the team through challenging times.", translation: "Ela demonstrou fortes habilidades de liderança ao guiar a equipe através de tempos difíceis." },
      { text: "We need to cultivate a growth mindset that embraces challenges and learning from failures.", translation: "Precisa cultivar uma mentalidade de crescimento que aceita desafios e aprende com os fracassos." },
      { text: "The conference brought together experts from various fields to discuss emerging trends.", translation: "O conferência reuniu especialistas de várias áreas para discutir tendências emergentes." },
      { text: "I was impressed by the innovative solutions proposed to address urban transportation challenges.", translation: "Fiquei impressionado com as soluções inovadoras propostas para enfrentar os desafios de transporte urbano." },
      { text: "He highlighted the importance of building strong interpersonal relationships in business.", translation: "Ele destacou a importância de construir fortes relações interpessoais nos negócios." },
      { text: "We should promote sustainable practices that reduce our carbon footprint on the environment.", translation: "Devemos promover práticas sustentáveis que reduzam nossa pegada de carbono no meio ambiente." },
      { text: "The book offers valuable insights into the complexities of human psychology.", translation: "O livro oferece insights valiosos sobre as complexidades da psicologia humana." },
      { text: "I am committed to contributing to the advancement of scientific knowledge through research.", translation: "Estou comprometido a contribuir para o avanço do conhecimento científico através da pesquisa." },
      { text: "She has become an advocate for accessible education for all children regardless of background.", translation: "Ela se tornou defensora da educação acessível para todas as crianças, independentemente da origem." },
      { text: "We should work towards creating a more equitable and just society for future generations.", translation: "Devemos trabalhar para criar uma sociedade mais equitativa e justa para as gerações futuras." },
      { text: "The program aims to empower young entrepreneurs to develop innovative business solutions.", translation: "O programa visa capacitar jovens empreendedores a desenvolver soluções de negócios inovadoras." },
      { text: "I have gained a deeper understanding of the importance of cultural sensitivity in global business.", translation: "Ganhei uma compreensão mais profunda da importância da sensibilidade cultural nos negócios globais." },
      { text: "He stressed the value of mentorship in helping individuals achieve their professional goals.", translation: "Ele enfatizou o valor da mentoria em ajudar indivíduos a alcançar seus objetivos profissionais." },
      { text: "We need to invest in renewable energy sources to ensure a sustainable future for all.", translation: "Precisamos investir em fontes de energia renovável para garantir um futuro sustentável para todos." },
      { text: "The research paper presents a compelling argument for the benefits of bilingual education.", translation: "O artigo de pesquisa apresenta um argumento convincente para os benefícios da educação bilíngue." },
      { text: "I was inspired by the stories of individuals who overcame significant challenges to succeed.", translation: "Fiquei inspirado pelas histórias de indivíduos que superaram desafios significativos para ter sucesso." },
      { text: "She has played a pivotal role in advancing gender equality in the workplace.", translation: "Ela desempenhou um papel fundamental no avanço da igualdade de gênero no local de trabalho." },
      { text: "We should promote interdisciplinary collaboration to address complex global challenges.", translation: "Devemos promover colaboração interdisciplinar para enfrentar desafios globais complexos." },
      { text: "The training program equipped participants with practical skills for the modern job market.", translation: "O programa de treinamento equipou os participantes com habilidades práticas para o mercado de trabalho moderno." },
      { text: "I have developed a strong appreciation for the arts and their role in expressing human emotion.", translation: "Desenvolvi uma forte apreciação pelas artes e seu papel na expressão da emoção humana." },
      { text: "He advocated for policies that support affordable housing and urban development.", translation: "Ele defendeu políticas que apoiam habitação acessível e desenvolvimento urbano." },
      { text: "We need to create more opportunities for underrepresented groups in STEM fields.", translation: "Precisa criar mais oportunidades para grupos sub-representados em áreas de STEM." },
      { text: "The symposium addressed the latest advancements in artificial intelligence and machine learning.", translation: "O simpósio abordou os mais recentes avanços em inteligência artificial e aprendizado de máquina." },
      { text: "I was amazed by the precision and elegance of the traditional dance performance.", translation: "Fiquei maravilhado com a precisão e elegância da apresentação de dança tradicional." },
      { text: "She has dedicated her career to improving healthcare access in rural communities.", translation: "Ela dedicou sua carreira a melhorar o acesso à saúde em comunidades rurais." },
      { text: "We should support local businesses and entrepreneurs to strengthen the community economy.", translation: "Devemos apoiar empresas e empreendedores locais para fortalecer a economia da comunidade." },
      { text: "The exhibition showcased a diverse collection of contemporary art from around the world.", translation: "A exposição apresentou uma coleção diversificada de arte contemporânea de todo o mundo." },
      { text: "I have learned the importance of adapting to change in an ever-evolving professional landscape.", translation: "Aprendi a importância de me adaptar a mudanças em um cenário profissional em constante evolução." },
      { text: "He emphasized the need for ethical leadership in guiding organizational culture and values.", translation: "Ele enfatizou a necessidade de liderança ética na orientação da cultura e valores organizacionais." },
      { text: "We should prioritize work-life balance to prevent burnout and maintain overall well-being.", translation: "Devemos priorizar o equilíbrio entre trabalho e vida para prevenir esgotamento e manter o bem-estar geral." },
      { text: "The case study demonstrated effective strategies for managing organizational change successfully.", translation: "O estudo de caso demonstrou estratégias eficazes para gerenciar a mudança organizacional com sucesso." },
      { text: "I have gained valuable experience through volunteer work and community service projects.", translation: "Ganhei experiência valiosa através de trabalho voluntário e projetos de serviço comunitário." },
      { text: "She has been recognized for her outstanding contributions to scientific research and innovation.", translation: "Ela foi reconhecida por suas contribuiçõesOutstanding para pesquisa científica e inovação." },
      { text: "We should foster an environment that encourages continuous improvement and excellence in all endeavors.", translation: "Devemos promover um ambiente que incentiva melhoria contínua e excelência em todos os esforços." },
      { text: "The podcast features interviews with industry experts discussing emerging trends and best practices.", translation: "O podcast apresenta entrevistas com especialistas do setor discutindo tendências emergentes e melhores práticas." },
      { text: "I was encouraged by the positive feedback from participants about the interactive workshop.", translation: "Fiquei encorajado pelo feedback positivo dos participantes sobre o workshop interativo." },
      { text: "He highlighted the role of technology in transforming education and making learning more accessible.", translation: "Ele destacou o papel da tecnologia na transformação da educação e na tornar a aprendizagem mais acessível." },
      { text: "We need to address the digital divide to ensure equal opportunities for all students.", translation: "Precisamos abordar a divisão digital para garantir oportunidades iguais para todos os estudantes." },
      { text: "The collaborative project brought together students from different backgrounds to work on a common goal.", translation: "O projeto colaborou reunindo estudantes de diferentes origens para trabalhar em um objetivo comum." },
      { text: "I have developed a greater sense of empathy and understanding towards people from diverse backgrounds.", translation: "Desenvolvi um maior senso de empatia e compreensão hacia pessoas de origens diversas." },
      { text: "She has been instrumental in promoting sustainable practices within the organization's operations.", translation: "Ela foi fundamental na promoção de práticas sustentáveis dentro das operações da organização." },
      { text: "We should celebrate diversity and create inclusive spaces where everyone feels valued and respected.", translation: "Devemos celebrar a diversidade e criar espaços inclusivos onde todos se sintam valorizados e respeitados." },
      { text: "The research findings will contribute to a better understanding of effective teaching methodologies.", translation: "Os resultados da pesquisa contribuirão para uma melhor compreensão de metodologias de ensino eficazes." },
      { text: "I was inspired to pursue continuous learning after attending the inspiring keynote presentation.", translation: "Fiquei inspirado a buscar aprendizagem contínua após assistir à apresentação inspiradora." },
      { text: "He emphasized the importance of building trust and credibility in professional relationships.", translation: "Ele enfatizou a importância de construir confiança e credibilidade em relacionamentos profissionais." },
      { text: "We should implement strategies that promote mental health awareness in the workplace.", translation: "Devemos implementar estratégias que promovam a conscientização sobre saúde mental no local de trabalho." },
      { text: "The initiative aims to reduce food waste and promote sustainable consumption practices.", translation: "A iniciativa visa reduzir o desperdício de alimentos e promover práticas de consumo sustentável." },
      { text: "I have come to appreciate the value of interdisciplinary knowledge in solving complex problems.", translation: "Comei a apreciar o valor do conhecimento interdisciplinar na resolução de problemas complexos." },
      { text: "She has been a strong advocate for environmental conservation and sustainable development.", translation: "Ela tem sido uma forte defensora da conservação ambiental e desenvolvimento sustentável." },
      { text: "We need to ensure that technology serves humanity and does not exacerbate existing inequalities.", translation: "Precisamos garantir que a tecnologia sirva à humanidade e não exacerbe desigualdades existentes." },
    ]
  },

  // ==================== B2 - Intermediário+ (80 frases) ====================
  {
    level: "B2",
    phrases: [
      { text: "The ability to communicate effectively in English opens many professional opportunities worldwide.", translation: "A capacidade de se comunicar efetivamente em inglês abre muitas oportunidades profissionais no mundo todo." },
      { text: "Despite the complexity of the grammar rules, she managed to write an excellent essay.", translation: "Apesar da complexidade das regras gramaticais, ela conseguiu escrever uma redação excelente." },
      { text: "The documentary provided a comprehensive overview of the environmental challenges we face.", translation: "O documentário forneceu uma visão geral abrangente dos desafios ambientais que enfrentamos." },
      { text: "He acknowledged that improving his pronunciation would require consistent effort over time.", translation: "Ele reconheceu que melhorar sua pronúncia exigiria esforço consistente ao longo do tempo." },
      { text: "The juxtaposition of ideas in the article stimulated profound intellectual discussion.", translation: "A justaposição de ideias no artigo estimulou uma discussão intelectual profunda." },
      { text: "Her sophisticated understanding of cultural nuances allows her to navigate international negotiations.", translation: "Sua compreensão sofisticada de nuances culturais permite navegar negociações internacionais." },
      { text: "Through meticulous analysis, the researcher revolutionized the field with groundbreaking discoveries.", translation: "Através de análise meticulosa, o pesquisador revolucionou o campo com descobertas inovadoras." },
      { text: "The unprecedented collaboration between institutions fostered breakthrough innovations across multiple disciplines.", translation: "A colaboração sem precedentes entre instituições fomentou inovações inovadoras em múltiplas disciplinas." },
      { text: "I have developed an appreciation for the subtleties of language that can only come from immersion.", translation: "Desenvolvi uma apreciação pelas sutilezas da linguagem que só podem vir da imersão." },
      { text: "She demonstrated remarkable resilience in overcoming the numerous obstacles she faced.", translation: "Ela demonstrou resiliência notável em superar os numerosos obstáculos que enfrentou." },
      { text: "The implementation of sustainable practices requires a fundamental shift in organizational mindset.", translation: "A implementação de práticas sustentáveis requer uma mudança fundamental na mentalidade organizacional." },
      { text: "His extensive knowledge of the subject matter enabled him to provide valuable insights to the team.", translation: "Seu amplo conhecimento do assunto permitiu fornecer insights valiosos para a equipe." },
      { text: "We should strive to create an inclusive environment that celebrates diverse perspectives and experiences.", translation: "Devemos nos esforçar para criar um ambiente inclusivo que celebra perspectivas e experiências diversas." },
      { text: "The integration of technology in education has transformed traditional pedagogical approaches significantly.", translation: "A integração da tecnologia na educação transformou abordagens pedagógicas tradicionais significativamente." },
      { text: "She advocated for evidence-based policies that address the root causes of social inequality.", translation: "Ela defendeu políticas baseadas em evidências que abordam as causas raiz da desigualdade social." },
      { text: "The multifaceted nature of the problem requires collaborative efforts from various stakeholders.", translation: "A natureza multifacetada do problema requer esforços colaborativos de várias partes interessadas." },
      { text: "I have come to understand that true mastery comes from embracing continuous learning and self-improvement.", translation: "Chei a entender que a verdadeira mestria vem de abraçar aprendizagem contínua e autoaperfeiçoamento." },
      { text: "The findings from the longitudinal study revealed significant trends in consumer behavior over time.", translation: "Os resultados do estudo longitudinal revelaram tendências significativas no comportamento do consumidor ao longo do tempo." },
      { text: "He emphasized the importance of maintaining ethical standards in the rapidly evolving field of technology.", translation: "Ele enfatizou a importância de manter padrões éticos no campo em rápida evolução da tecnologia." },
      { text: "We need to develop strategies that balance economic growth with environmental sustainability.", translation: "Precisa desenvolver estratégias que equilibrem o crescimento econômico com a sustentabilidade ambiental." },
      { text: "The symposium brought together leading experts to discuss emerging trends in renewable energy technologies.", translation: "O simpósio reuniu especialistas líderes para discutir tendências emergentes em tecnologias de energia renovável." },
      { text: "I was deeply impressed by the innovative approaches being implemented to address climate change challenges.", translation: "Fiquei profundamente impressionado com as abordagens inovadoras sendo implementadas para enfrentar os desafios das mudanças climáticas." },
      { text: "She has contributed significantly to advancing gender equality through her advocacy and leadership.", translation: "Ela contribuiu significativamente para o avanço da igualdade de gênero através de sua defesa e liderança." },
      { text: "The integration of artificial intelligence in healthcare has the potential to revolutionize patient care.", translation: "A integração da inteligência artificial na saúde tem o potencial de revolucionar o cuidado com o paciente." },
      { text: "We should work towards creating a more equitable society where everyone has access to quality education.", translation: "Devemos trabalhar para criar uma sociedade mais equitativa onde todos tenham acesso a educação de qualidade." },
      { text: "The comprehensive analysis revealed patterns that were not immediately apparent to most observers.", translation: "A análise abrangente revelou padrões que não eram imediatamente aparentes para a maioria dos observadores." },
      { text: "I have learned to appreciate the value of constructive feedback in accelerating personal and professional growth.", translation: "Aprendi a apreciar o valor do feedback construtivo em acelerar o crescimento pessoal e profissional." },
      { text: "He highlighted the need for comprehensive digital literacy programs to prepare students for the future workforce.", translation: "Ele destacou a necessidade de programas abrangentes de alfabetização digital para preparar estudantes para a futura força de trabalho." },
      { text: "We must address the systemic barriers that prevent equal opportunities for underrepresented communities.", translation: "Devemos abordar as barreiras sistêmicas que impedem oportunidades iguais para comunidades sub-representadas." },
      { text: "The innovative solution addresses multiple challenges simultaneously, demonstrating remarkable creative problem-solving.", translation: "A solução inovadora aborda múltiplos desafios simultaneamente, demonstrando notável resolução criativa de problemas." },
      { text: "I have gained a deeper understanding of the interconnectedness between economic development and social progress.", translation: "Ganhei uma compreensão mais profunda da interconexão entre desenvolvimento econômico e progresso social." },
      { text: "She has been recognized internationally for her pioneering research in sustainable agricultural practices.", translation: "Ela foi reconhecida internacionalmente por sua pesquisa pioneira em práticas agrícolas sustentáveis." },
      { text: "We should foster a culture of innovation that encourages experimentation and learning from failure.", translation: "Devemos promover uma cultura de inovação que incentive a experimentação e aprendizagem com o fracasso." },
      { text: "The comprehensive framework provides a structured approach to addressing complex societal challenges.", translation: "O framework abrangente fornece uma abordagem estruturada para enfrentar desafios sociais complexos." },
      { text: "I was inspired by the transformative impact that mentorship can have on emerging professionals.", translation: "Fiquei inspirado pelo impacto transformador que a mentoria pode ter em profissionais emergentes." },
      { text: "He emphasized the critical role that emotional intelligence plays in effective leadership and team management.", translation: "Ele enfatizou o papel crítico que a inteligência emocional desempenha na liderança eficaz e gestão de equipe." },
      { text: "We need to prioritize mental health support in educational institutions to ensure student well-being.", translation: "Precisamos priorizar o apoio à saúde mental em instituições educacionais para garantir o bem-estar estudantil." },
      { text: "The cross-cultural exchange program has enriched participants' understanding of global perspectives and diversity.", translation: "O programa de intercâmbio cultural enriquceu a compreensão dos participantes sobre perspectivas globais e diversidade." },
      { text: "I have developed a greater appreciation for the complexities of cross-cultural communication in professional settings.", translation: "Desenvolvi uma maior apreciação pelas complexidades da comunicação intercultural em ambientes profissionais." },
      { text: "She demonstrated exceptional leadership in navigating the organization through challenging economic conditions.", translation: "Ela demonstrou liderança excepcional ao navegar a organização através de condições econômicas desafiadoras." },
      { text: "We should implement comprehensive strategies that address both immediate needs and long-term sustainability goals.", translation: "Devemos implementar estratégias abrangentes que abordem necessidades imediatas e objetivos de sustentabilidade de longo prazo." },
      { text: "The case study highlighted the effectiveness of collaborative approaches in resolving complex disputes.", translation: "O estudo de caso destacou a eficácia de abordagens colaborativas na resolução de disputas complexas." },
      { text: "I have come to realize that meaningful connections with others are fundamental to personal fulfillment.", translation: "Chei a perceber que conexões significativas com os outros são fundamentais para realização pessoal." },
      { text: "He advocated for policies that promote work-life balance and support employee well-being in modern workplaces.", translation: "Ele defendeu políticas que promovem equilíbrio entre trabalho e vida e apoiam o bem-estar dos funcionários em locais de trabalho modernos." },
      { text: "We need to develop innovative solutions that address the unique challenges faced by remote teams.", translation: "Precisa desenvolver soluções inovadoras que abordem os desafios únicos enfrentados por equipes remotas." },
      { text: "The research findings have significant implications for shaping future educational policies and practices.", translation: "Os resultados da pesquisa têm implicações significativas para moldar futuras políticas e práticas educacionais." },
      { text: "I was amazed by the depth of insight that can emerge from thoughtful and structured philosophical inquiry.", translation: "Fiquei maravilhado com a profundidade de insights que podem emergir de questionamentos filosóficos estruturados e reflexivos." },
      { text: "She has dedicated her career to advancing accessible healthcare solutions for underserved communities.", translation: "Ela dedicou sua carreira a avançar soluções de saúde acessíveis para comunidades carentes." },
      { text: "We should promote interdisciplinary collaboration that brings together diverse expertise to solve complex problems.", translation: "Devemos promover colaboração interdisciplinar que reúna expertise diversa para resolver problemas complexos." },
      { text: "The strategic partnership has enabled the organization to expand its impact significantly across multiple regions.", translation: "A parceria estratégica permitiu que a organização expandisse seu impacto significativamente em múltiplas regiões." },
      { text: "I have learned that true leadership involves empowering others to reach their full potential.", translation: "Aprendi que verdadeira liderança envolve capacitar outros para alcançar seu potencial máximo." },
      { text: "He emphasized the need for transparent communication and accountability in maintaining public trust.", translation: "Ele enfatizou a necessidade de comunicação transparente e responsabilidade na manutenção da confiança pública." },
      { text: "We must prioritize sustainable development practices that protect our planet for future generations.", translation: "Devemos priorizar práticas de desenvolvimento sustentável que protejam nosso planeta para as gerações futuras." },
      { text: "The comprehensive evaluation revealed the significant impact of the community development program on local residents.", translation: "A avaliação abrangente revelou o impacto significativo do programa de desenvolvimento comunitário nos residentes locais." },
      { text: "I have gained valuable insights into effective change management strategies through practical experience.", translation: "Ganhei insights valiosos sobre estratégias eficazes de gestão de mudanças através de experiência prática." },
      { text: "She has been instrumental in developing innovative curriculum that integrates technology with experiential learning.", translation: "Ela foi fundamental no desenvolvimento de currículo inovador que integra tecnologia com aprendizagem experiencial." },
      { text: "We should create more opportunities for intergenerational knowledge exchange and mentorship programs.", translation: "Devemos criar mais oportunidades para troca de conhecimento intergeracional e programas de mentoria." },
      { text: "The independent evaluation confirmed the positive outcomes of the social intervention program in the community.", translation: "A avaliação independente confirmou os resultados positivos do programa de intervenção social na comunidade." },
      { text: "I have come to understand the profound impact that art and creativity can have on emotional healing.", translation: "Chei a entender o impacto profundo que a arte e a criatividade podem ter na cura emocional." },
      { text: "He advocated for comprehensive immigration reforms that balance security with humanitarian considerations.", translation: "Ele defendeu reformas migratórias abrangentes que equilibram segurança com considerações humanitárias." },
      { text: "We need to invest in infrastructure that supports sustainable urban development and reduces carbon emissions.", translation: "Precisamos investir em infraestrutura que apoia desenvolvimento urbano sustentável e reduz emissões de carbono." },
      { text: "The longitudinal research provided compelling evidence about the long-term benefits of early childhood education.", translation: "A pesquisa longitudinal forneceu evidências convincentes sobre os benefícios de longo prazo da educação infantil." },
      { text: "I was inspired by the resilience and determination of community leaders working to create positive change.", translation: "Fiquei inspirado pela resiliência e determinação de líderes comunitários que trabalham para criar mudanças positivas." },
      { text: "She demonstrated exceptional diplomatic skills in mediating conflicts between stakeholders with opposing interests.", translation: "Ela demonstrou habilidades diplomáticas excepcionais em mediar conflitos entre partes com interesses opostos." },
      { text: "We should develop comprehensive approaches to address the intersection of public health and environmental sustainability.", translation: "Devemos desenvolver abordagens abrangentes para abordar a interseção de saúde pública e sustentabilidade ambiental." },
      { text: "The strategic plan outlines clear objectives for achieving sustainable growth over the next decade.", translation: "O plano estratégico descreve objetivos claros para alcançar crescimento sustentável na próxima década." },
      { text: "I have learned the importance of building authentic relationships based on mutual trust and respect.", translation: "Aprendi a importância de construir relações autênticas baseadas em confiança e respeito mútuos." },
      { text: "He highlighted the critical need for financial literacy education to empower young adults in managing their finances.", translation: "Ele destacou a necessidade crítica de educação financeira para capacitar jovens adultos em gerenciar suas finanças." },
      { text: "We must create more inclusive spaces that celebrate diversity and promote equal opportunities for all.", translation: "Devemos criar espaços mais inclusivos que celebrem diversidade e promovam oportunidades iguais para todos." },
      { text: "The comprehensive review identified key factors contributing to the success of the international development initiative.", translation: "A revisão abrangente identificou fatores principais que contribuem para o sucesso da iniciativa de desenvolvimento internacional." },
      { text: "I have gained a deeper appreciation for the role of cultural heritage in shaping community identity and cohesion.", translation: "Ganhei uma apreciação mais profunda pelo papel do patrimônio cultural na formação de identidade e coesão comunitária." },
      { text: "She has championed initiatives that promote access to clean water and sanitation in developing regions.", translation: "Ela defendeu iniciativas que promovem acesso a água limpa e saneamento em regiões em desenvolvimento." },
      { text: "We should work collaboratively to address the global challenges that transcend national borders and require unified action.", translation: "Devemos trabalhar colaborativamente para abordar desafios globais que transcendem fronteiras nacionais e requerem ação unificada." },
      { text: "The comprehensive assessment highlighted the need for targeted interventions to support vulnerable populations.", translation: "A avaliação abrangente destacou a necessidade de intervenções direcionadas para apoiar populações vulneráveis." },
      { text: "I was deeply moved by the stories of individuals who have overcome adversity through perseverance and hope.", translation: "Fiquei profundamente comovido pelas histórias de indivíduos que superaram adversidade através de perseverança e esperança." },
      { text: "He emphasized the value of lifelong learning in adapting to the rapidly changing professional landscape.", translation: "Ele enfatizou o valor da aprendizagem ao longo da vida em se adaptar ao cenário profissional em rápida mudança." },
      { text: "We need to implement comprehensive cybersecurity measures to protect sensitive information and maintain public trust.", translation: "Precisamos implementar medidas abrangentes de cibersegurança para proteger informações sensíveis e manter a confiança pública." },
      { text: "The strategic framework provides a roadmap for achieving gender parity in leadership positions across sectors.", translation: "O framework estratégico fornece um roteiro para alcançar paridade de gênero em posições de liderança em todos os setores." },
    ]
  },

  // ==================== C1 - Avançado (60 frases) ====================
  {
    level: "C1",
    phrases: [
      { text: "The juxtaposition of contrasting ideas in the article stimulated profound intellectual discussion.", translation: "A justaposição de ideias contrastantes no artigo estimulou uma discussão intelectual profunda." },
      { text: "Her sophisticated understanding of cultural nuances allows her to navigate international business negotiations.", translation: "Sua compreensão sofisticada de nuances culturais permite navegar negociações internacionais de negócios." },
      { text: "The benevolent organization implemented sustainable solutions to address the community's long-term needs.", translation: "A organização benevolente implementou soluções sustentáveis para atender às necessidades de longo prazo da comunidade." },
      { text: "His comprehensive knowledge of literature encompasses multiple genres and historical periods.", translation: "Seu conhecimento abrangente de literatura abrange múltiplos gêneros e períodos históricos." },
      { text: "The ephemeral nature of social media fame underscores the importance of substantial achievements.", translation: "A natureza efêmera da fama nas redes sociais sublinha a importância de conquistas substanciais." },
      { text: "Through meticulous analysis and unprecedented methodology, the researcher revolutionized the field.", translation: "Através de análise meticulosa e metodologia sem precedentes, o pesquisador revolucionou o campo." },
      { text: "The quintessential characteristic of profound knowledge is the ability to elucidate complex concepts.", translation: "A característica quintessencial do conhecimento profundo é a habilidade de elucidar conceitos complexos." },
      { text: "The unprecedented collaboration between the institutions fostered groundbreaking discoveries.", translation: "A colaboração sem precedentes entre as instituições promoveu descobertas inovadoras." },
      { text: "The confluence of technological advancement and environmental consciousness presents both challenges and opportunities.", translation: "A confluência do avanço tecnológico e consciência ambiental apresenta desafios e oportunidades." },
      { text: "Her nuanced perspective on the matter revealed the intricate interplay of social, economic, and political factors.", translation: "Sua perspectiva matizada sobre o assunto revelou a complexa interação de fatores sociais, econômicos e políticos." },
      { text: "The systematic approach to problem-solving demonstrated exceptional analytical rigor and creativity.", translation: "A abordagem sistemática para resolução de problemas demonstrou rigor analítico e criatividade excepcionais." },
      { text: "His prolific contributions to scientific research have established him as a preeminent authority in his field.", translation: "Suas contribuições prolíficas para a pesquisa científica o estabeleceram como autoridade eminente em sua área." },
      { text: "The comprehensive treatise provided a nuanced analysis of the sociopolitical dynamics shaping contemporary society.", translation: "O tratado abrangente forneceu uma análise matizada das dinâmicas sociopolíticas que moldam a sociedade contemporânea." },
      { text: "The sophisticated algorithm leverages machine learning to adaptively optimize performance across diverse scenarios.", translation: "O algoritmo sofisticado aproveita aprendizado de máquina para otimizar adaptativamente o desempenho em diversos cenários." },
      { text: "Her exemplary leadership during the crisis demonstrated unwavering commitment to ethical principles and stakeholder interests.", translation: "Sua liderança exemplar durante a crise demonstrou compromisso inabalável com princípios éticos e interesses das partes interessadas." },
      { text: "The multifaceted nature of the challenge requires integrated solutions that address interconnected problems.", translation: "A natureza multifacetada do desafio requer soluções integradas que abordem problemas interconectados." },
      { text: "His seminal work has fundamentally transformed our understanding of the underlying mechanisms governing natural phenomena.", translation: "Seu trabalho seminal transformou fundamentalmente nossa compreensão dos mecanismos subjacentes que governam fenômenos naturais." },
      { text: "The strategic implementation of the policy has yielded measurable improvements in organizational efficiency.", translation: "A implementação estratégica da política produziu melhorias mensuráveis na eficiência organizacional." },
      { text: "Her pioneering research in regenerative medicine has opened new frontiers in therapeutic interventions.", translation: "Sua pesquisa pioneira em medicina regenerativa abriu novas fronteiras em intervenções terapêuticas." },
      { text: "The comprehensive framework integrates multiple theoretical perspectives to provide a holistic understanding of the phenomenon.", translation: "O framework abrangente integra múltiplas perspectivas teóricas para fornecer uma compreensão holística do fenômeno." },
      { text: "His nuanced interpretation of the historical events challenged conventional wisdom and sparked scholarly debate.", translation: "Sua interpretação matizada dos eventos históricos desafiou a sabedoria convencional e desencadeou debates acadêmicos." },
      { text: "The systematic review identified critical gaps in the existing literature and proposed avenues for future research.", translation: "A revisão sistemática identificou lacunas críticas na literatura existente e propôs caminhos para pesquisas futuras." },
      { text: "Her exceptional ability to synthesize complex information into accessible insights has made her an invaluable resource.", translation: "Sua habilidade excepcional de sintetizar informações complexas em insights acessíveis a tornou um recurso inestimável." },
      { text: "The interdisciplinary approach to addressing climate change requires collaboration across scientific and policy domains.", translation: "A abordagem interdisciplinar para enfrentar as mudanças climáticas requer colaboração entre domínios científicos e de políticas." },
      { text: "His profound understanding of market dynamics has enabled strategic decisions that consistently outperformed industry benchmarks.", translation: "Sua compreensão profunda da dinâmica de mercado permitiu decisões estratégicas que consistentemente superaram os benchmarks da indústria." },
      { text: "The comprehensive analysis revealed underlying patterns that explain the complex phenomenon under investigation.", translation: "A análise abrangente revelou padrões subjacentes que explicam o fenômeno complexo sob investigação." },
      { text: "Her innovative pedagogical approach has significantly enhanced student engagement and learning outcomes in higher education.", translation: "Sua abordagem pedagógica inovadora melhorou significativamente o engajamento dos estudantes e resultados de aprendizagem no ensino superior." },
      { text: "The integration of sustainable practices into business operations represents a paradigm shift in corporate responsibility.", translation: "A integração de práticas sustentáveis nas operações de negócios representa uma mudança de paradigma na responsabilidade corporativa." },
      { text: "His distinguished career in public service exemplifies the profound impact that dedicated individuals can have on society.", translation: "Sua carreira distinta em serviço público exemplifica o impacto profundo que indivíduos dedicados podem ter na sociedade." },
      { text: "The comprehensive assessment highlighted the efficacy of the intervention in achieving desired outcomes across multiple dimensions.", translation: "A avaliação abrangente destacou a eficácia da intervenção na достижении resultados desejados em múltiplas dimensões." },
      { text: "Her strategic vision for the organization's future has positioned it as a leader in sustainable innovation.", translation: "Sua visão estratégica para o futuro da organização a posicionou como líder em inovação sustentável." },
      { text: "The systematic documentation of best practices has provided invaluable guidance for practitioners in the field.", translation: "A documentação sistemática de melhores práticas forneceu orientação inestimável para profissionais na área." },
      { text: "His meticulous attention to detail ensured the accuracy and reliability of the research findings.", translation: "Sua atenção meticulosa aos detalhes assegurou a precisão e confiabilidade dos resultados da pesquisa." },
      { text: "The comprehensive evaluation of the program revealed significant improvements in participant outcomes and community impact.", translation: "A avaliação abrangente do programa revelou melhorias significativas nos resultados dos participantes e impacto na comunidade." },
      { text: "Her seminal contributions to the field have established new paradigms for understanding complex systems.", translation: "Suas contribuições seminais para o campo estabeleceram novos paradigmas para entender sistemas complexos." },
      { text: "The strategic partnership has enabled the integration of complementary capabilities to address mutual challenges.", translation: "A parceria estratégica permitiu a integração de capacidades complementares para abordar desafios mútuos." },
      { text: "His profound commitment to social justice has driven transformative changes in public policy and community development.", translation: "Seu profundo compromisso com a justiça social impulsionou mudanças transformadoras em políticas públicas e desenvolvimento comunitário." },
      { text: "The comprehensive framework provides structured guidance for implementing evidence-based practices across diverse contexts.", translation: "O framework abrangente fornece orientação estruturada para implementar práticas baseadas em evidências em contextos diversos." },
      { text: "Her exceptional communication skills enabled successful negotiation of complex agreements between competing interests.", translation: "Suas habilidades de comunicação excepcionais permitiram negociação bem-sucedida de acordos complexos entre interesses concorrentes." },
      { text: "The systematic approach to capacity building has empowered communities to take ownership of their development trajectory.", translation: "A abordagem sistemática de construção de capacidades capacitou comunidades a assumir a propriedade de sua trajetória de desenvolvimento." },
      { text: "His distinguished scholarship has advanced understanding of fundamental principles governing complex adaptive systems.", translation: "Sua bolsa distinguida avançou a compreensão de princípios fundamentais que governam sistemas adaptativos complexos." },
      { text: "The comprehensive review synthesized findings from multiple studies to provide a nuanced understanding of the phenomenon.", translation: "A revisão abrangente sintetizou resultados de múltiplos estudos para fornecer uma compreensão matizada do fenômeno." },
      { text: "Her visionary leadership has inspired unprecedented collaboration among stakeholders to address shared challenges.", translation: "Sua liderança visionária inspirou colaboração sem precedentes entre partes interessadas para abordar desafios compartilhados." },
      { text: "The innovative solution addresses systemic barriers while creating sustainable pathways for future development.", translation: "A solução inovadora aborda barreiras sistêmicas enquanto cria caminhos sustentáveis para desenvolvimento futuro." },
      { text: "His meticulous research methodology has become a model for rigorous inquiry in the field.", translation: "Sua metodologia de pesquisa meticulosa se tornou um modelo para investigação rigorosa no campo." },
      { text: "The comprehensive strategy integrates multiple intervention modalities to maximize impact across target populations.", translation: "A estratégia abrangente integra múltiplas modalidades de intervenção para maximizar o impacto entre populações-alvo." },
      { text: "Her profound empathy and cultural sensitivity have enabled meaningful connections with diverse communities worldwide.", translation: "Sua profunda empatia e sensibilidade cultural permitiram conexões significativas com comunidades diversas no mundo." },
      { text: "The systematic documentation of lessons learned has created an institutional knowledge base for continuous improvement.", translation: "A documentação sistemática de lições aprendidas criou uma base de conhecimento institucional para melhoria contínua." },
      { text: "His distinguished career exemplifies the integration of academic rigor with practical application in addressing real-world challenges.", translation: "Sua carreira distinta exemplifica a integração de rigor acadêmico com aplicação prática no enfrentamento de desafios do mundo real." },
      { text: "The comprehensive framework offers a systematic approach to navigating complex ethical dilemmas in professional practice.", translation: "O framework abrangente oferece uma abordagem sistemática para navegar dilemas éticos complexos na prática profissional." },
      { text: "Her innovative approach to problem-solving has catalyzed transformative changes across multiple sectors.", translation: "Sua abordagem inovadora para resolução de problemas catalisou mudanças transformadoras em múltiplos setores." },
      { text: "The strategic initiatives have positioned the organization as a thought leader in sustainable development.", translation: "As iniciativas estratégicas posicionaram a organização como líder de pensamento em desenvolvimento sustentável." },
      { text: "His profound expertise in the subject matter has made him a sought-after advisor for policy development.", translation: "Sua profunda expertise no assunto o tornou um conselheiro procurado para desenvolvimento de políticas." },
      { text: "The comprehensive analysis provides actionable insights for stakeholders seeking to optimize resource allocation.", translation: "A análise abrangente fornece insights acionáveis para partes interessadas que buscam otimizar a alocação de recursos." },
      { text: "Her exemplary dedication to advancing educational equity has created lasting impact in underserved communities.", translation: "Sua dedicação exemplar para avançar a equidade educacional criou impacto duradouro em comunidades carentes." },
    ]
  },

  // ==================== C2 - Fluente (40 frases) ====================
  {
    level: "C2",
    phrases: [
      { text: "The ephemeral nature of social media fame underscores the importance of substantive achievements over fleeting visibility.", translation: "A natureza efêmera da fama nas redes sociais sublinha a importância de conquistas substanciais sobre visibilidade passageira." },
      { text: "Through meticulous analysis and unprecedented methodology, the researcher revolutionized the field with paradigm-shifting discoveries.", translation: "Através de análise meticulosa e metodologia sem precedentes, o pesquisador revolucionou o campo com descobertas que mudam paradigmas." },
      { text: "The quintessential characteristic of profound knowledge is the capacity to elucidate complex concepts with exceptional clarity.", translation: "A característica quintessencial do conhecimento profundo é a capacidade de elucidar conceitos complexos com clareza excepcional." },
      { text: "The unprecedented collaboration between the institutions fostered groundbreaking discoveries that transcended disciplinary boundaries.", translation: "A colaboração sem precedentes entre as instituições promoveu descobertas inovadoras que transcendiam fronteiras disciplinares." },
      { text: "The confluence of technological advancement and environmental consciousness presents both challenges and unprecedented opportunities for sustainable development.", translation: "A confluência do avanço tecnológico e consciência ambiental apresenta desafios e oportunidades sem precedentes para desenvolvimento sustentável." },
      { text: "Her nuanced perspective on the matter revealed the intricate interplay of social, economic, political, and cultural factors.", translation: "Sua perspectiva matizada sobre o assunto revelou a complexa interação de fatores sociais, econômicos, políticos e culturais." },
      { text: "The systematic approach to problem-solving demonstrated exceptional analytical rigor, creativity, and pragmatic effectiveness.", translation: "A abordagem sistemática para resolução de problemas demonstrou rigor analítico excepcional, criatividade e eficácia pragmática." },
      { text: "His prolific contributions to scientific research have established him as a preeminent authority in his specialized domain.", translation: "Suas contribuições prolíficas para a pesquisa científica o estabeleceram como autoridade eminente em seu domínio especializado." },
      { text: "The comprehensive treatise provided a nuanced and comprehensive analysis of the sociopolitical dynamics shaping contemporary society.", translation: "O tratado abrangente forneceu uma análise matizada e abrangente das dinâmicas sociopolíticas que moldam a sociedade contemporânea." },
      { text: "The sophisticated algorithm leverages advanced machine learning techniques to adaptively optimize performance across diverse scenarios.", translation: "O algoritmo sofisticado aproveita técnicas avançadas de aprendizado de máquina para otimizar adaptativamente o desempenho em diversos cenários." },
      { text: "Her exemplary leadership during the crisis demonstrated unwavering commitment to ethical principles, transparency, and stakeholder interests.", translation: "Sua liderança exemplar durante a crise demonstrou compromisso inabalável com princípios éticos, transparência e interesses das partes interessadas." },
      { text: "The multifaceted nature of the global challenge requires integrated solutions that address interconnected environmental, social, and economic problems.", translation: "A natureza multifacetada do desafio global requer soluções integradas que abordam problemas ambientais, sociais e econômicos interconectados." },
      { text: "His seminal work has fundamentally transformed our understanding of the underlying mechanisms governing complex natural phenomena.", translation: "Seu trabalho seminal transformou fundamentalmente nossa compreensão dos mecanismos subjacentes que governam fenômenos naturais complexos." },
      { text: "The strategic implementation of the comprehensive policy has yielded measurable improvements in organizational efficiency, employee satisfaction, and community impact.", translation: "A implementação estratégica da política abrangente produziu melhorias mensuráveis na eficiência organizacional, satisfação dos funcionários e impacto na comunidade." },
      { text: "Her pioneering research in regenerative medicine has opened new frontiers in therapeutic interventions, offering hope for previously incurable conditions.", translation: "Sua pesquisa pioneira em medicina regenerativa abriu novas fronteiras em intervenções terapêuticas, oferecendo esperança para condições anteriormente incuráveis." },
      { text: "The comprehensive framework integrates multiple theoretical perspectives to provide a holistic and nuanced understanding of the complex phenomenon.", translation: "O framework abrangente integra múltiplas perspectivas teóricas para fornecer uma compreensão holística e matizada do fenômeno complexo." },
      { text: "His nuanced interpretation of historical events challenged conventional wisdom, sparked intense scholarly debate, and revised established narratives.", translation: "Sua interpretação matizada de eventos históricos desafiou a sabedoria convencional, desencadeou intensos debates acadêmicos e revisou narrativas estabelecidas." },
      { text: "The systematic review identified critical gaps in the existing literature and proposed innovative avenues for future multidisciplinary research.", translation: "A revisão sistemática identificou lacunas críticas na literatura existente e propôs caminhos inovadores para pesquisas futuras multidisciplinares." },
      { text: "Her exceptional ability to synthesize complex information from diverse sources into accessible, actionable insights has made her an invaluable resource.", translation: "Sua habilidade excepcional de sintetizar informações complexas de diversas fontes em insights acessíveis e acionáveis a tornou um recurso inestimável." },
      { text: "The interdisciplinary approach to addressing climate change requires unprecedented collaboration across scientific, political, economic, and social domains.", translation: "A abordagem interdisciplinar para enfrentar as mudanças climáticas requer colaboração sem precedentes entre domínios científicos, políticos, econômicos e sociais." },
      { text: "His profound understanding of global market dynamics has enabled strategic decisions that consistently outperformed industry benchmarks and competitor expectations.", translation: "Sua compreensão profunda da dinâmica global do mercado permitiu decisões estratégicas que consistentemente superaram benchmarks da indústria e expectativas dos concorrentes." },
      { text: "The comprehensive analysis revealed underlying patterns that comprehensively explain the complex phenomenon under rigorous scientific investigation.", translation: "A análise abrangente revelou padrões subjacentes que explicam completamente o fenômeno complexo sob investigação científica rigorosa." },
      { text: "Her innovative pedagogical approach has significantly enhanced student engagement, critical thinking, and measurable learning outcomes in higher education.", translation: "Sua abordagem pedagógica inovadora melhorou significativamente o engajamento dos estudantes, pensamento crítico e resultados mensuráveis de aprendizagem no ensino superior." },
      { text: "The integration of sustainable practices into business operations represents a fundamental paradigm shift in corporate social responsibility and environmental stewardship.", translation: "A integração de práticas sustentáveis nas operações de negócios representa uma mudança de paradigma fundamental na responsabilidade social corporativa e gestão ambiental." },
      { text: "His distinguished career in public service exemplifies the profound and lasting impact that dedicated, principled individuals can have on society.", translation: "Sua carreira distinta em serviço público exemplifica o impacto profundo e duradouro que indivíduos dedicados e princípios podem ter na sociedade." },
      { text: "The comprehensive assessment highlighted the exceptional efficacy of the intervention in achieving desired outcomes across multiple measurable dimensions.", translation: "A avaliação abrangente destacou a eficácia excepcional da intervenção na достижении resultados desejados em múltiplas dimensões mensuráveis." },
      { text: "Her strategic vision for the organization's future has positioned it as an undisputed leader in sustainable innovation and responsible corporate citizenship.", translation: "Sua visão estratégica para o futuro da organização a posicionou como líder inquestionável em inovação sustentável e cidadania corporativa responsável." },
      { text: "The systematic documentation of best practices has provided invaluable guidance for practitioners seeking to implement evidence-based interventions.", translation: "A documentação sistemática de melhores práticas forneceu orientação inestimável para profissionais que buscam implementar intervenções baseadas em evidências." },
      { text: "His meticulous attention to methodological detail ensured the exceptional accuracy, reliability, and reproducibility of the research findings.", translation: "Sua atenção meticulosa aos detalhes metodológicos assegurou a precisão excepcional, confiabilidade e reprodutibilidade dos resultados da pesquisa." },
      { text: "The comprehensive evaluation of the multi-year program revealed significant improvements in participant outcomes and measurable community impact.", translation: "A avaliação abrangente do programa de vários anos revelou melhorias significativas nos resultados dos participantes e impacto mensurável na comunidade." },
      { text: "Her seminal contributions to theoretical frameworks have established new paradigms for understanding complex adaptive systems in natural and social contexts.", translation: "Suas contribuições seminais para frameworks teóricos estabeleceram novos paradigmas para entender sistemas adaptativos complexos em contextos naturais e sociais." },
      { text: "The strategic partnership has enabled the integration of complementary capabilities to address mutual challenges that neither could solve independently.", translation: "A parceria estratégica permitiu a integração de capacidades complementares para abordar desafios mútuos que nenhum poderia resolver independentemente." },
      { text: "His profound commitment to social justice has driven transformative changes in public policy, institutional practices, and community development initiatives.", translation: "Seu profundo compromisso com a justiça social impulsionou mudanças transformadoras em políticas públicas, práticas institucionais e iniciativas de desenvolvimento comunitário." },
      { text: "The comprehensive framework provides structured guidance for implementing ethical decision-making frameworks in complex professional contexts.", translation: "O framework abrangente fornece orientação estruturada para implementar frameworks de tomada de decisão ética em contextos profissionais complexos." },
      { text: "Her exceptional communication and negotiation skills enabled successful resolution of complex disputes between parties with fundamentally opposing interests.", translation: "Suas habilidades excepcionais de comunicação e negociação permitiram resolução bem-sucedida de disputas complexas entre partes com interesses fundamentalmente opostos." },
      { text: "The systematic approach to capacity building has empowered communities to take meaningful ownership of their sustainable development trajectory.", translation: "A abordagem sistemática de construção de capacidades capacitou comunidades a assumir propriedade significativa de sua trajetória de desenvolvimento sustentável." },
      { text: "His distinguished scholarship has fundamentally advanced understanding of the fundamental principles governing complex adaptive systems across disciplines.", translation: "Sua bolsa distinguida avançou fundamentalmente a compreensão dos princípios fundamentais que governam sistemas adaptativos complexos em diferentes disciplinas." },
      { text: "The comprehensive review masterfully synthesized findings from numerous studies to provide an integrated and nuanced understanding of the phenomenon.", translation: "A revisão abrangente sintetizou magistralmente resultados de numerosos estudos para fornecer uma compreensão integrada e matizada do fenômeno." },
      { text: "Her visionary leadership has inspired unprecedented levels of collaboration among diverse stakeholders to address complex shared challenges.", translation: "Sua liderança visionária inspirou níveis sem precedentes de colaboração entre diversas partes interessadas para abordar desafios complexos compartilhados." },
      { text: "The innovative solution comprehensively addresses systemic barriers while creating sustainable pathways for continued future development and improvement.", translation: "A solução inovadora aborda barreiras sistêmicas de forma abrangente enquanto cria caminhos sustentáveis para desenvolvimento e melhoria futuros contínuos." },
      { text: "His meticulous research methodology has become the definitive model for rigorous scientific inquiry within the field and beyond.", translation: "Sua metodologia de pesquisa meticulosa se tornou o modelo definitivo para investigação científica rigorosa no campo e além." },
    ]
  }
]

async function seed() {
  console.log('Iniciando seed completo do FluentSRS...')
  
  let totalPhrases = 0
  let totalWords = 0
  let totalLinks = 0

  for (const levelData of phrasesData) {
    const level = levelData.level
    const phrases = levelData.phrases

    console.log(`Processando ${level} - ${phrases.length} frases`)

    for (const p of phrases) {
      const existing = await prisma.phrase.findUnique({ where: { text: p.text } })
      if (existing) continue

      const wordTexts = extractKeyWords(p.text)
      const wordIds = []

      for (const wt of wordTexts) {
        let word = await prisma.word.findUnique({ where: { word: wt } })
        if (!word) {
          word = await prisma.word.create({
            data: { word: wt, level, translation: null }
          })
          totalWords++
        }
        wordIds.push(word.id)
      }

      const phrase = await prisma.phrase.create({
        data: {
          text: p.text,
          translation: p.translation,
          level
        }
      })
      totalPhrases++

      for (const wid of wordIds) {
        await prisma.phraseWord.create({
          data: { phraseId: phrase.id, wordId: wid }
        }).catch(() => {})
        totalLinks++
      }

      await prisma.sRSRecord.create({
        data: {
          phraseId: phrase.id,
          entityType: 0,
          status: 'new',
          nextReview: new Date(Date.now() + Math.floor(Math.random() * 86400000)),
          easeFactor: 2.5,
          interval: 0,
          repetitions: 0
        }
      })
    }
  }

  console.log(`\n✓ Seed completo!`)
  console.log(`  - ${totalPhrases} frases`)
  console.log(`  - ${totalWords} palavras novas`)
  console.log(`  - ${totalLinks} links`)
  console.log(`  - Total de palavras no banco: ${await prisma.word.count()}`)
  
  await prisma.$disconnect()
}

function extractKeyWords(text) {
  const stopWords = new Set([
    'the', 'a', 'an', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'and', 'or', 'but', 
    'is', 'are', 'was', 'were', 'be', 'been', 'have', 'has', 'had', 'do', 'does', 'did', 
    'will', 'would', 'can', 'could', 'should', 'may', 'might', 'shall', 'must',
    'it', 'its', 'this', 'that', 'these', 'those', 'i', 'you', 'he', 'she', 'we', 'they',
    'me', 'him', 'her', 'us', 'them', 'my', 'your', 'his', 'her', 'our', 'their', 'not',
    'no', 'nor', 'so', 'if', 'as', 'from', 'by', 'up', 'down', 'about', 'into', 'through',
    'during', 'before', 'after', 'above', 'below', 'between', 'out', 'off', 'over', 'under',
    'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how',
    'all', 'each', 'every', 'both', 'few', 'more', 'most', 'other', 'some', 'such',
    'only', 'own', 'same', 'than', 'too', 'very', 'just', 'now', 'get', 'got', 'go', 'went'
  ])

  return [...new Set(
    text.toLowerCase()
      .replace(/[^a-z\s']/g, '')
      .split(/\s+/)
      .filter(w => w.length > 1 && !stopWords.has(w))
  )]
}

seed().catch(e => {
  console.error(e)
  process.exit(1)
})